// <auto-generated />
namespace BooksInventory.DataAccess.EF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Use_FullTextSearch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Use_FullTextSearch));
        
        string IMigrationMetadata.Id
        {
            get { return "202405270951096_Use_FullTextSearch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
